// Generated by Wrangler by running `wrangler types`

interface Env {
	SLEEPY: KVNamespace;
	SECRET: string;
	USER: string;
	LEARNMORE: string;
	REPO: string;
	MORETEXT: string;
	BG: string;
	ASSETS: Fetcher;
}
